### ISSUE TITLE
Reduce requirements

### ISSUE THREAD

**Issue by AstraLuma** [rowanlupton/pylodon#94]
IMHO, `requirements.txt` should only be what you directly depend on. If you want more extensive version pinning (freezing, locking), something like a constraints file should be used.

(pipfile/pipenv can also be used, but I've found deploying with pipenv to be challenging in the past.)

More information:
* https://stackoverflow.com/questions/34645821/pip-constraints-files

**Comment by rowanlupton** [comment]
i believe that i have just pruned this down (i actually went through the code and added things i was directly importing instead of going through requirements and being like "uhhh i think i directly need that?") in [my last commit](https://github.com/rowanlupton/pylodon/commit/5eaa92ca70a067d24a843b88809e91139c705a76)
